[package]
name = "fsr"
version = "0.1.0"
authors = ["pmann84 <peterdmann28@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.3.0"
ansi_term = "0.12"
filetime = "0.2"
chrono = "0.4"